.a -> .dylib

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,7 +21,7 @@ else
 	done
 
 	for lib in capnp kj; do
-		test -f "$(brew --prefix)/lib/lib${lib}.a" || error "*** dependency missing: ‘$(brew --prefix)/lib/lib${lib}.a’. Install dependency and/or update ‘local.rave’ with correct path."
+		test -f "$(brew --prefix)/lib/lib${lib}.dylib" || error "*** dependency missing: ‘$(brew --prefix)/lib/lib${lib}.a’. Install dependency and/or update ‘local.rave’ with correct path."
 	done
 fi
 
