Fix config: test for either .a or .dylib libs (#21)
* .a -> .dylib

* Test for either .dylib or .a libs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -21,8 +21,9 @@ else
 	done
 
 	for lib in capnp kj; do
-		test -f "$(brew --prefix)/lib/lib${lib}.a" || error "*** dependency missing: ‘$(brew --prefix)/lib/lib${lib}.a’. Install dependency and/or update ‘local.rave’ with correct path."
-	done
+		test -f "$(brew --prefix)/lib/lib${lib}.dylib" || test -f "$(brew --prefix)/lib/lib${lib}.a" \
+		|| error "*** dependency missing: ‘$(brew --prefix)/lib/lib${lib}.{dylib,a}’. Install dependency and/or update ‘local.rave’ with correct path."
+done
 fi
 
 # ========================
